# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161001_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
