# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20161008_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_id',
        ),
    ]
