# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractAddressModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('country_code', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=127)),
                ('district', models.CharField(max_length=127)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('gender', models.CharField(max_length=1)),
                ('family_status', models.CharField(max_length=32)),
                ('education_level', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualEmail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('email', models.EmailField(max_length=254)),
                ('individual_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Individual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(blank=True, max_length=127)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('individual_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Individual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualPhone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('number', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=16)),
                ('individual_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Individual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('entity_type', models.CharField(max_length=32, verbose_name='Entity type')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCompanyManager',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserCompany')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualAddress',
            fields=[
                ('abstractaddressmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.AbstractAddressModel')),
                ('individual_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Individual')),
            ],
            options={
                'abstract': False,
            },
            bases=('crm.abstractaddressmodel',),
        ),
    ]
