# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown'), ('O', 'Other')], max_length=1)),
                ('title', models.CharField(blank=True, max_length=127, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('family_status', models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Single'), ('W', 'Widow'), ('P', 'Partner'), ('D', 'Divorced')], max_length=32, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('E', 'Elementery'), ('V', 'Vocational'), ('H', 'High'), ('D', 'Degree'), ('MD', 'Master degree'), ('DD', 'Doctoral degree'), ('PD', 'Professional degree')], max_length=32, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboundContactAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('zip_code', models.CharField(max_length=16)),
                ('city', models.CharField(blank=True, max_length=127)),
                ('district', models.CharField(blank=True, max_length=127)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('inbound_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.InboundContact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboundContactEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('email', models.EmailField(max_length=254)),
                ('inbound_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.InboundContact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboundContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('number', models.CharField(max_length=64)),
                ('type', models.CharField(blank=True, max_length=16)),
                ('inbound_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.InboundContact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown'), ('O', 'Other')], max_length=1)),
                ('title', models.CharField(blank=True, max_length=127, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('family_status', models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Single'), ('W', 'Widow'), ('P', 'Partner'), ('D', 'Divorced')], max_length=32, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('E', 'Elementery'), ('V', 'Vocational'), ('H', 'High'), ('D', 'Degree'), ('MD', 'Master degree'), ('DD', 'Doctoral degree'), ('PD', 'Professional degree')], max_length=32, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('zip_code', models.CharField(max_length=16)),
                ('city', models.CharField(blank=True, max_length=127)),
                ('district', models.CharField(blank=True, max_length=127)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Individual')),
            ],
            options={
                'verbose_name_plural': 'Individual addresses',
            },
        ),
        migrations.CreateModel(
            name='IndividualEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('email', models.EmailField(max_length=254)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Individual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('number', models.CharField(max_length=64)),
                ('type', models.CharField(blank=True, max_length=16)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Individual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutboundContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('entity_type', models.CharField(choices=[('ST', 'Sole trade'), ('SV', 'Sole venture'), ('LP', 'Limited partnership'), ('GP', 'General partnership'), ('LLC', 'Limited liability company'), ('CIC', 'Community interest company'), ('JV', 'Joint venture'), ('JSC', 'Joint stock company'), ('PLC', 'Public limited company')], max_length=32, verbose_name='Entity type')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User companies',
            },
        ),
        migrations.CreateModel(
            name='UserCompanyConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserCompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inboundcontact',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Individual'),
        ),
    ]
