# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercompanymanager',
            old_name='user_company_id',
            new_name='company_id',
        ),
    ]
