# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20161008_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercompanymanager',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='usercompanymanager',
            old_name='user_id',
            new_name='user',
        ),
    ]
