# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20161022_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundcontact',
            name='is_cleansed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inboundcontact',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inboundcontactaddress',
            name='is_cleansed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inboundcontactaddress',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inboundcontactemail',
            name='is_cleansed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inboundcontactemail',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inboundcontactphone',
            name='is_cleansed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inboundcontactphone',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_cleansed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualaddress',
            name='is_cleansed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualaddress',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualemail',
            name='is_cleansed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualemail',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualphone',
            name='is_cleansed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualphone',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
