# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20161008_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCompanyManager',
            new_name='UserCompanyConnection',
        ),
    ]
