# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20161023_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboundcontactaddress',
            old_name='city',
            new_name='administrative_area',
        ),
        migrations.RenameField(
            model_name='inboundcontactaddress',
            old_name='address',
            new_name='formatted_address',
        ),
        migrations.RenameField(
            model_name='individualaddress',
            old_name='city',
            new_name='administrative_area',
        ),
        migrations.RenameField(
            model_name='individualaddress',
            old_name='address',
            new_name='formatted_address',
        ),
        migrations.RemoveField(
            model_name='inboundcontactaddress',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='individualaddress',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='inboundcontactaddress',
            name='county',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='inboundcontactaddress',
            name='final_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='inboundcontactaddress',
            name='latitude',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='inboundcontactaddress',
            name='locality',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='inboundcontactaddress',
            name='longitude',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='inboundcontactaddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='inboundcontactaddress',
            name='postal_code_suffix',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='inboundcontactaddress',
            name='route',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inboundcontactaddress',
            name='street_number',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='individualaddress',
            name='county',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='individualaddress',
            name='final_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='individualaddress',
            name='latitude',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='individualaddress',
            name='locality',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='individualaddress',
            name='longitude',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='individualaddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='individualaddress',
            name='postal_code_suffix',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='individualaddress',
            name='route',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='individualaddress',
            name='street_number',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
