# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20161008_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualaddress',
            old_name='individual_id',
            new_name='individual',
        ),
        migrations.RenameField(
            model_name='individualemail',
            old_name='individual_id',
            new_name='individual',
        ),
        migrations.RenameField(
            model_name='individualname',
            old_name='individual_id',
            new_name='individual',
        ),
        migrations.RenameField(
            model_name='individualphone',
            old_name='individual_id',
            new_name='individual',
        ),
    ]
