# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20161023_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundcontactaddress',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inboundcontactaddress',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inboundcontactaddress',
            name='street_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='individualaddress',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='individualaddress',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='individualaddress',
            name='street_number',
            field=models.IntegerField(null=True),
        ),
    ]
