# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20161008_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundContact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('gender', models.CharField(max_length=1)),
                ('title', models.CharField(blank=True, max_length=127, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('family_status', models.CharField(max_length=32)),
                ('education_level', models.CharField(max_length=32)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboundContactAddress',
            fields=[
                ('abstractaddressmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.AbstractAddressModel')),
                ('inbound_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.InboundContact')),
            ],
            options={
                'abstract': False,
            },
            bases=('crm.abstractaddressmodel',),
        ),
        migrations.CreateModel(
            name='InboundContactEmail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('email', models.EmailField(max_length=254)),
                ('inbound_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.InboundContact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboundContactPhone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('number', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=16)),
                ('inbound_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.InboundContact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutboundContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='individualname',
            name='individual',
        ),
        migrations.AlterModelOptions(
            name='individualaddress',
            options={'verbose_name_plural': 'Individual addresses'},
        ),
        migrations.AlterModelOptions(
            name='usercompany',
            options={'verbose_name_plural': 'User companies'},
        ),
        migrations.AddField(
            model_name='individual',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='title',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.DeleteModel(
            name='IndividualName',
        ),
        migrations.AddField(
            model_name='outboundcontact',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Individual'),
        ),
        migrations.AddField(
            model_name='inboundcontact',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Individual'),
        ),
    ]
