# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20161023_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundcontactaddress',
            name='administrative_area',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='inboundcontactaddress',
            name='district',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='inboundcontactaddress',
            name='postal_code_suffix',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='individualaddress',
            name='administrative_area',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='individualaddress',
            name='district',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='individualaddress',
            name='postal_code_suffix',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
