# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20161009_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundcontact',
            name='education_level',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='inboundcontact',
            name='family_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='education_level',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='family_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
