# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20161009_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractaddressmodel',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='abstractaddressmodel',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='inboundcontact',
            name='education_level',
            field=models.CharField(blank=True, choices=[('E', 'Elementery'), ('V', 'Vocational'), ('H', 'High'), ('D', 'Degree'), ('MD', 'Master degree'), ('DD', 'Doctoral degree'), ('PD', 'Professional degree')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='inboundcontact',
            name='family_status',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Single'), ('W', 'Widow'), ('P', 'Partner'), ('D', 'Divorced')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='inboundcontact',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='inboundcontactphone',
            name='type',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='individual',
            name='education_level',
            field=models.CharField(blank=True, choices=[('E', 'Elementery'), ('V', 'Vocational'), ('H', 'High'), ('D', 'Degree'), ('MD', 'Master degree'), ('DD', 'Doctoral degree'), ('PD', 'Professional degree')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='family_status',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Single'), ('W', 'Widow'), ('P', 'Partner'), ('D', 'Divorced')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='individualphone',
            name='type',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='entity_type',
            field=models.CharField(choices=[('ST', 'Sole trade'), ('SV', 'Sole venture'), ('LP', 'Limited partnership'), ('GP', 'General partnership'), ('LLC', 'Limited liability company'), ('CIC', 'Community interest company'), ('JV', 'Joint venture'), ('JSC', 'Joint stock company'), ('PLC', 'Public limited company')], max_length=32, verbose_name='Entity type'),
        ),
    ]
