# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20161106_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundcontactphoneinfo',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
