# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20161016_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualaddress',
            name='individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Individual'),
        ),
        migrations.AlterField(
            model_name='individualemail',
            name='individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Individual'),
        ),
        migrations.AlterField(
            model_name='individualphone',
            name='individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Individual'),
        ),
    ]
