# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_outboundcontactphoneinfo_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundcontactemailinfo',
            name='number_of_bounced',
            field=models.IntegerField(default=0),
        ),
    ]
