# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20161016_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualaddress',
            name='individual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.Individual'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualemail',
            name='individual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.Individual'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualphone',
            name='individual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.Individual'),
            preserve_default=False,
        ),
    ]
