from django.conf.urls import url

from rest_framework_jwt.views import (
    obtain_jwt_token,
    refresh_jwt_token,
    verify_jwt_token
)

from api.views import (
    CampaignListAPI,
    CampaignCreateAPI,
    CampaignRetrieveAPI,
    CampaignUpdateAPI,
    CampaignDestroyAPI,
    IndividualListAPI,
    IndividualCreateAPI,
    IndividualRetrieveAPI,
    IndividualUpdateAPI,
    IndividualDestroyAPI,
    InboundContactListAPI,
    InboundContactCreateAPI,
    InboundContactRetrieveAPI,
    InboundContactUpdateAPI,
    InboundContactDestroyAPI,
    OutboundContactListAPI,
    OutboundContactCreateAPI,
    OutboundContactRetrieveAPI,
    OutboundContactUpdateAPI,
    OutboundContactDestroyAPI,
    SourceListAPI,
    SourceCreateAPI,
    SourceRetrieveAPI,
    SourceUpdateAPI,
    SourceDestroyAPI,
    SourceTypeListAPI,
    SourceTypeCreateAPI,
    SourceTypeRetrieveAPI,
    SourceTypeUpdateAPI,
    SourceTypeDestroyAPI
)


urlpatterns = [
    # Token
    url(
        r'^auth/token/$',
        obtain_jwt_token,
    ),
    url(
        r'^auth/token/refresh/$',
        refresh_jwt_token
    ),
    url(
        r'^auth/token/verify/$',
        verify_jwt_token
    ),

    # List APIs
    url(
        r'^individuals/$',
        IndividualListAPI.as_view(),
        name='api-individuals'
    ),
    url(
        r'^individuals/create/$',
        IndividualCreateAPI.as_view(),
        name='api-individual-create'
    ),
    url(
        r'^individuals/(?P<pk>\d+)/$',
        IndividualRetrieveAPI.as_view(),
        name='api-individual-retrieve'
    ),
    url(
        r'^individuals/update/(?P<pk>\d+)/$',
        IndividualUpdateAPI.as_view(),
        name='api-individual-update'
    ),
    url(
        r'^individuals/delete/(?P<pk>\d+)/$',
        IndividualDestroyAPI.as_view(),
        name='api-individual-delete'
    ),
    url(
        r'^inbound-contacts/$',
        InboundContactListAPI.as_view(),
        name='api-inbound-contacts'
    ),
    url(
        r'^inbound-contacts/create/$',
        InboundContactCreateAPI.as_view(),
        name='api-inbound-contact-create'
    ),
    url(
        r'^inbound-contacts/(?P<pk>\d+)/$',
        InboundContactRetrieveAPI.as_view(),
        name='api-inbound-contact-retrieve'
    ),
    url(
        r'^inbound-contacts/update/(?P<pk>\d+)/$',
        InboundContactUpdateAPI.as_view(),
        name='api-inbound-contact-update'
    ),
    url(
        r'^inbound-contacts/delete/(?P<pk>\d+)/$',
        InboundContactDestroyAPI.as_view(),
        name='api-inbound-contact-delete'
    ),
    url(
        r'^outbound-contacts/$',
        OutboundContactListAPI.as_view(),
        name='api-outbound-contacts'
    ),
    url(
        r'^outbound-contacts/create/$',
        OutboundContactCreateAPI.as_view(),
        name='api-outbound-contact-create'
    ),
    url(
        r'^outbound-contacts/(?P<pk>\d+)/$',
        OutboundContactRetrieveAPI.as_view(),
        name='api-outbound-contact-retrieve'
    ),
    url(
        r'^outbound-contacts/update/(?P<pk>\d+)/$',
        OutboundContactUpdateAPI.as_view(),
        name='api-outbound-contact-update'
    ),
    url(
        r'^outbound-contacts/delete/(?P<pk>\d+)/$',
        OutboundContactDestroyAPI.as_view(),
        name='api-outbound-contact-delete'
    ),
    url(
        r'^campaigns/$',
        CampaignListAPI.as_view(),
        name='api-campaigns'
    ),
    url(
        r'^campaigns/create/$',
        CampaignCreateAPI.as_view(),
        name='api-campaign-create'
    ),
    url(
        r'^campaigns/(?P<pk>\d+)/$',
        CampaignRetrieveAPI.as_view(),
        name='api-campaign-retrieve'
    ),
    url(
        r'^campaigns/update/(?P<pk>\d+)/$',
        CampaignUpdateAPI.as_view(),
        name='api-campaign-update'
    ),
    url(
        r'^campaigns/delete/(?P<pk>\d+)/$',
        CampaignDestroyAPI.as_view(),
        name='api-campaign-delete'
    ),
    url(
        r'^sources/$',
        SourceListAPI.as_view(),
        name='api-sources'
    ),
    url(
        r'^sources/create/$',
        SourceCreateAPI.as_view(),
        name='api-source-create'
    ),
    url(
        r'^sources/(?P<pk>\d+)/$',
        SourceRetrieveAPI.as_view(),
        name='api-source-retrieve'
    ),
    url(
        r'^sources/update/(?P<pk>\d+)/$',
        SourceUpdateAPI.as_view(),
        name='api-source-update'
    ),
    url(
        r'^sources/delete/(?P<pk>\d+)/$',
        SourceDestroyAPI.as_view(),
        name='api-source-delete'
    ),
    url(
        r'^source-types/$',
        SourceTypeListAPI.as_view(),
        name='api-source-types'
    ),
    url(
        r'^source-types/create/$',
        SourceTypeCreateAPI.as_view(),
        name='api-source-type-create'
    ),
    url(
        r'^source-types/(?P<pk>\d+)/$',
        SourceTypeRetrieveAPI.as_view(),
        name='api-source-type-retrieve'
    ),
    url(
        r'^source-types/update/(?P<pk>\d+)/$',
        SourceTypeUpdateAPI.as_view(),
        name='api-source-type-update'
    ),
    url(
        r'^source-types/delete/(?P<pk>\d+)/$',
        SourceTypeDestroyAPI.as_view(),
        name='api-source-type-destroy'
    ),
]
